package com.condominio.persistence.model;

public enum CategoriaMovimiento {
    ADMINISTRACION_CUOTAS, SERVICIOS_PUBLICOS, ASEO_JARDINERIA, MANTENIMIENTO_REPARACIONES,
    PISCINA, SEGURIDAD_ACCESO, EVENTOS_DECORACION, PERSONAL_MANO_OBRA, MULTAS, OTROS
}
